# 配置文件环境变量名
GLOBAL_SETTING_ENV_NAME = 'UVR5_WEB_SETTINGS'

# 根据手机号限制短信验证码发送频次
LIMIT_EMAIL_SNED_BY_RECIPENT = '1/minute'

# 根据IP限制短信验证码发送频次
LIMIT_EMAIL_VERIFICATION_CODE_BY_IP = '100/hour'

# 短信验证码有效期(秒)
EMAIL_VERIFICATION_CODE_EXPIRES = 5 * 60
